from azure.storage.blob import BlobServiceClient

# Connect to Blob Storage
connection_string = "your_connection_string"
container_name = "your_container"
blob_name = "your_file.xlsx"

# Download the file locally first
blob_service_client = BlobServiceClient.from_connection_string(connection_string)
blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)

with open("temp_file.xlsx", "wb") as download_file:
    download_file.write(blob_client.download_blob().readall())

# Now read with pandas
df = pd.read_excel("temp_file.xlsx")

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('RW_ACTUALS_ALL_Processed_PRF.csv')

df

,CASENO,COUNTRY_SHORT,TITLE,CASE_TYPE,CASE_DESCRIPTION,CASE_OCCURENCE_DATE
0,52502,DE,Kohlestaub-Leckage Brenner 42,Environment,Aus der Isolierung am Brenner 42 ist ein Kohle...,29/01/2025
1,47726,NL,Grachtwater Temperatuur,Environment,Het grachtwater heeft de 25C uur gemiddelde be...,07/08/2024
2,48776,NO,Utsläpp av kylvatten från det interna kylvatte...,Environment,Utsläpp av kylvatten från det interna kylvatte...,23/08/2024
3,49329,UK,CW Discharge Pipework Failure,Environment,CW Discharge Pipework failure. Main CW pimp In...,07/10/2024
4,47405,UK,Main Cooling Water - Pipe failure - Loss of co...,Environment,"Unit was on outage, with the open cycle CW pum...",21/07/2024
...,...,...,...,...,...,...
21015,36124,DE,Stromkabel Beleuchtung nicht mehr ordnungsgemäß,Safety,Dach Kesselhaus 1: Stromkabel Beleuchtung nich...,27/06/2023
21016,39175,UK,Eye irritation,Safety,Apprentice craftsman had eye irritation whilst...,25/10/2023
21017,44084,DE,Sperrung Klärschlammannahme der KA Großkrotzen...,Environment,Aufgrund von Überschreitung des Grenzwertes AO...,07/09/2023
21018,51156,DE,Wet Floor Positive Observation,NaN,"As I was taking the stairs in Float building, ...",03/12/2024
21019,52477,NO,WP12.5 avfall blandat mellan olika WP R7.13,Operational loss,WP12.5 avfall blandat mellan olika WP R7.13,30/01/2025

In [3]:
df1 = pd.read_csv('Default of credit card clients.csv')

In [4]:
df1

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000,1,3,1,39,0,0,0,0,...,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29996,29997,150000,1,3,2,43,-1,-1,-1,-1,...,8979,5190,0,1837,3526,8998,129,0,0,0
29997,29998,30000,1,2,2,37,4,3,2,-1,...,20878,20582,19357,0,0,22000,4200,2000,3100,1
29998,29999,80000,1,3,1,41,1,-1,0,0,...,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
29999,30000,50000,1,2,1,46,0,0,0,0,...,36535,32428,15313,2078,1800,1430,1000,1000,1000,1